// Code generated by "stringer -type Type"; DO NOT EDIT.

package scan

import "strconv"

const _Type_name = "EOFErrorLeftParenLeftBrackLeftBraceQuoteQuasiQuoteUnquoteUnquoteSplicingFalseTrueDotFixnumFlonumStringSymbolRightParenRightBrackRightBraceCharLiteralAssignCharGreaterOrEqualIdentifierNumberOperatorOpRationalSemicolonSpace"

var _Type_index = [...]uint8{0, 3, 8, 17, 26, 35, 40, 50, 57, 72, 77, 81, 84, 90, 96, 102, 108, 118, 128, 138, 149, 155, 159, 173, 183, 189, 197, 199, 207, 216, 221}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
