// Code generated by "stringer -type Type"; DO NOT EDIT.

package scan

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EOF-0]
	_ = x[Error-1]
	_ = x[LeftParen-2]
	_ = x[LeftBrack-3]
	_ = x[LeftBrace-4]
	_ = x[Quote-5]
	_ = x[QuasiQuote-6]
	_ = x[Unquote-7]
	_ = x[UnquoteSplicing-8]
	_ = x[False-9]
	_ = x[True-10]
	_ = x[Dot-11]
	_ = x[Ellipsis-12]
	_ = x[Fixnum-13]
	_ = x[Flonum-14]
	_ = x[Char-15]
	_ = x[Symbol-16]
	_ = x[String-17]
	_ = x[RightParen-18]
	_ = x[RightBrack-19]
	_ = x[RightBrace-20]
}

const _Type_name = "EOFErrorLeftParenLeftBrackLeftBraceQuoteQuasiQuoteUnquoteUnquoteSplicingFalseTrueDotEllipsisFixnumFlonumCharSymbolStringRightParenRightBrackRightBrace"

var _Type_index = [...]uint8{0, 3, 8, 17, 26, 35, 40, 50, 57, 72, 77, 81, 84, 92, 98, 104, 108, 114, 120, 130, 140, 150}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
